// app/(member)/user/compliance/statement/page.tsx
'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Download, FileText } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { ApiClientError, getMemberToken, memberFetch } from '@/lib/api/client';
import {
  formatStatementMoney,
  statementStatusBadgeVariant,
  type MemberStatementDto,
} from '@/lib/compliance/statement-shared';

function SummaryRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between gap-4 py-2 text-sm">
      <span className="text-muted-foreground">{label}</span>
      <span className="font-medium tabular-nums">{value}</span>
    </div>
  );
}

export default function StatementPage() {
  const [items, setItems] = useState<MemberStatementDto[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [downloading, setDownloading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(() => {
    setLoading(true);
    setError(null);
    memberFetch<MemberStatementDto[]>('/api/member/compliance/statements')
      .then((list) => {
        setItems(list);
        setSelectedId((prev) => {
          if (prev && list.some((s) => s.id === prev)) return prev;
          return list[0]?.id ?? null;
        });
      })
      .catch((err) => setError(err instanceof ApiClientError ? err.message : '加载失败'))
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  const selected = useMemo(
    () => items.find((s) => s.id === selectedId) ?? null,
    [items, selectedId],
  );

  const downloadPdf = async (id: string) => {
    setDownloading(true);
    setError(null);
    try {
      const token = getMemberToken();
      const res = await fetch(`/api/member/compliance/statements/${id}/pdf`, {
        headers: token ? { Authorization: `Bearer ${token}` } : {},
      });
      if (!res.ok) {
        const json = await res.json().catch(() => null);
        throw new Error((json as { message?: string })?.message ?? 'PDF 下载失败');
      }
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      window.open(url, '_blank');
      setTimeout(() => URL.revokeObjectURL(url), 60_000);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'PDF 下载失败');
    } finally {
      setDownloading(false);
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold">月度对账单</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          查看历史对账单与税务服务完成状态；对账单于次月 16–20 日生成并推送通知（F-61）
        </p>
      </div>

      {error && (
        <Alert variant="destructive">
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      {loading && <p className="text-muted-foreground">加载中…</p>}

      {!loading && items.length === 0 && (
        <Card>
          <CardContent className="flex flex-col items-center gap-3 py-12 text-center">
            <FileText className="h-10 w-10 text-muted-foreground" />
            <p className="font-medium">暂无对账单</p>
            <p className="max-w-md text-sm text-muted-foreground">
              完成上月收入、费用录入与申报后，系统将在次月 16–20 日自动生成对账单并发送通知。
            </p>
          </CardContent>
        </Card>
      )}

      {!loading && items.length > 0 && (
        <>
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base">对账单列表</CardTitle>
              <CardDescription>点击行查看当月服务完成摘要</CardDescription>
            </CardHeader>
            <CardContent className="p-0">
              <div className="hidden overflow-x-auto md:block">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b bg-muted/40 text-left">
                      <th className="p-3 font-medium">账期</th>
                      <th className="p-3 font-medium text-right">收入</th>
                      <th className="p-3 font-medium text-right">成本</th>
                      <th className="p-3 font-medium text-right">利润</th>
                      <th className="p-3 font-medium text-right">预缴税额</th>
                      <th className="p-3 font-medium">状态</th>
                      <th className="p-3 font-medium">操作</th>
                    </tr>
                  </thead>
                  <tbody>
                    {items.map((s) => {
                      const active = s.id === selectedId;
                      return (
                        <tr
                          key={s.id}
                          className={`cursor-pointer border-b transition-colors hover:bg-muted/30 ${active ? 'bg-muted/50' : ''}`}
                          onClick={() => setSelectedId(s.id)}
                        >
                          <td className="p-3 font-medium">{s.period}</td>
                          <td className="p-3 text-right tabular-nums">
                            {formatStatementMoney(s.summary.revenue)}
                          </td>
                          <td className="p-3 text-right tabular-nums">
                            {formatStatementMoney(s.summary.cost)}
                          </td>
                          <td className="p-3 text-right tabular-nums">
                            {formatStatementMoney(s.summary.profit)}
                          </td>
                          <td className="p-3 text-right tabular-nums">
                            {formatStatementMoney(s.summary.taxTotal)}
                          </td>
                          <td className="p-3">
                            <Badge
                              variant={statementStatusBadgeVariant(s.status, s.serviceComplete)}
                            >
                              {s.serviceComplete ? '已完成' : s.statusLabel}
                            </Badge>
                          </td>
                          <td className="p-3">
                            {s.hasPdf && (
                              <Button
                                size="sm"
                                variant="outline"
                                onClick={(e) => {
                                  e.stopPropagation();
                                  void downloadPdf(s.id);
                                }}
                                disabled={downloading}
                              >
                                <Download className="mr-1 h-3.5 w-3.5" />
                                PDF
                              </Button>
                            )}
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>

              <div className="divide-y md:hidden">
                {items.map((s) => {
                  const active = s.id === selectedId;
                  return (
                    <button
                      key={s.id}
                      type="button"
                      className={`w-full px-4 py-3 text-left transition-colors ${active ? 'bg-muted/50' : ''}`}
                      onClick={() => setSelectedId(s.id)}
                    >
                      <div className="flex items-center justify-between gap-2">
                        <span className="font-medium">{s.period}</span>
                        <Badge
                          variant={statementStatusBadgeVariant(s.status, s.serviceComplete)}
                        >
                          {s.serviceComplete ? '已完成' : s.statusLabel}
                        </Badge>
                      </div>
                      <p className="mt-1 text-xs text-muted-foreground">
                        利润 {formatStatementMoney(s.summary.profit)} · 税额{' '}
                        {formatStatementMoney(s.summary.taxTotal)}
                      </p>
                    </button>
                  );
                })}
              </div>
            </CardContent>
          </Card>

          {selected && (
            <Card className="border-primary/20">
              <CardHeader>
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div>
                    <CardTitle className="flex items-center gap-2 text-lg">
                      {selected.year}年{selected.month}月 · 税务服务完成报告
                      {selected.serviceComplete && (
                        <CheckCircle2 className="h-5 w-5 text-emerald-600" aria-hidden />
                      )}
                    </CardTitle>
                    <CardDescription className="mt-1">
                      {selected.sentAt
                        ? `已于 ${new Date(selected.sentAt).toLocaleString('zh-CN')} 发送通知`
                        : '对账单已生成，通知发送后将在此显示时间'}
                    </CardDescription>
                  </div>
                  {selected.hasPdf && (
                    <Button
                      variant="default"
                      size="sm"
                      disabled={downloading}
                      onClick={() => void downloadPdf(selected.id)}
                    >
                      <Download className="mr-1.5 h-4 w-4" />
                      {downloading ? '下载中…' : '下载 PDF'}
                    </Button>
                  )}
                </div>
              </CardHeader>
              <CardContent className="divide-y rounded-lg border bg-muted/20">
                <SummaryRow label="本月收入" value={formatStatementMoney(selected.summary.revenue)} />
                <SummaryRow label="本月成本" value={formatStatementMoney(selected.summary.cost)} />
                <SummaryRow label="本月利润" value={formatStatementMoney(selected.summary.profit)} />
                <SummaryRow
                  label="本月预缴税额"
                  value={formatStatementMoney(selected.summary.taxTotal)}
                />
                <SummaryRow
                  label="累计年度利润"
                  value={formatStatementMoney(selected.summary.cumulativeProfit)}
                />
                <SummaryRow label="申报状态" value={selected.summary.filingStatus} />
              </CardContent>
            </Card>
          )}
        </>
      )}
    </div>
  );
}

// web/src/views/frontend/compliance/statement.vue
<!-- P-12 月度对账单 -->
<template>
  <section class="bg-white/70 backdrop-blur-xl rounded-[48px] shadow-clay-card border border-[#d1d9e6]/40 p-8 md:p-10">
    <div class="mb-8">
      <h2 class="font-heading font-black text-2xl text-clay-foreground">月度对账单</h2>
      <p class="text-xs text-clay-muted mt-1">查看历史对账单与服务完成状态</p>
    </div>

    <div v-if="loading" class="py-16 text-center">
      <ArtSvgIcon icon="ri:loader-4-line" class="text-3xl text-clay-accent animate-spin mx-auto" />
    </div>

    <div v-else-if="list.length === 0" class="py-16 text-center text-clay-muted font-medium">
      暂无对账单，每月 16 日后由顾问生成
    </div>

    <template v-else>
      <div class="overflow-x-auto rounded-2xl mb-8">
        <table class="w-full text-sm">
          <thead>
            <tr class="text-left text-[10px] font-black text-clay-muted uppercase tracking-widest border-b">
              <th class="py-3 px-4">月份</th>
              <th class="py-3 px-4">收入</th>
              <th class="py-3 px-4">成本</th>
              <th class="py-3 px-4">利润</th>
              <th class="py-3 px-4">预缴税额</th>
              <th class="py-3 px-4">状态</th>
              <th class="py-3 px-4">操作</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="row in list"
              :key="row.id"
              class="border-b border-gray-100 cursor-pointer transition-colors"
              :class="selected?.id === row.id ? 'bg-blue-50' : 'hover:bg-white/50'"
              @click="selected = row"
            >
              <td class="py-3 px-4 font-bold text-clay-foreground">{{ row.period }}</td>
              <td class="py-3 px-4">¥{{ formatMoney(row.revenue) }}</td>
              <td class="py-3 px-4">¥{{ formatMoney(row.cost) }}</td>
              <td class="py-3 px-4 font-bold" :class="row.profit >= 0 ? 'text-clay-success' : 'text-red-500'">
                ¥{{ formatMoney(row.profit) }}
              </td>
              <td class="py-3 px-4">¥{{ formatMoney(row.prepaidTax) }}</td>
              <td class="py-3 px-4">
                <span class="text-xs font-bold px-2 py-0.5 rounded-full" :class="row.status === 'completed' ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-clay-muted'">
                  {{ row.status === 'completed' ? '✅ 已完成' : '处理中' }}
                </span>
              </td>
              <td class="py-3 px-4">
                <button
                  type="button"
                  class="text-sm font-bold text-clay-accent hover:underline flex items-center gap-1"
                  @click.stop="downloadPdf(row)"
                >
                  <ArtSvgIcon icon="ri:file-pdf-line" />PDF
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- 详情卡片 -->
      <div v-if="selected" class="p-6 rounded-[32px] bg-[#f0f3f8] shadow-clay-pressed">
        <h3 class="font-heading font-black text-lg text-clay-foreground mb-4">{{ selected.period }} 服务完成摘要</h3>
        <div class="grid sm:grid-cols-2 gap-4 text-sm">
          <div class="p-4 rounded-2xl bg-white shadow-clay-btn">
            <span class="block text-[10px] font-black text-clay-muted uppercase mb-1">本月收入</span>
            <span class="font-black text-xl text-clay-foreground">¥{{ formatMoney(selected.revenue) }}</span>
          </div>
          <div class="p-4 rounded-2xl bg-white shadow-clay-btn">
            <span class="block text-[10px] font-black text-clay-muted uppercase mb-1">本月成本</span>
            <span class="font-black text-xl text-clay-foreground">¥{{ formatMoney(selected.cost) }}</span>
          </div>
          <div class="p-4 rounded-2xl bg-white shadow-clay-btn">
            <span class="block text-[10px] font-black text-clay-muted uppercase mb-1">本月利润</span>
            <span class="font-black text-xl" :class="selected.profit >= 0 ? 'text-clay-success' : 'text-red-500'">
              ¥{{ formatMoney(selected.profit) }}
            </span>
          </div>
          <div class="p-4 rounded-2xl bg-white shadow-clay-btn">
            <span class="block text-[10px] font-black text-clay-muted uppercase mb-1">本月预缴税额</span>
            <span class="font-black text-xl text-clay-accent">¥{{ formatMoney(selected.prepaidTax) }}</span>
          </div>
        </div>
        <div class="mt-4 pt-4 border-t border-gray-200/50 flex flex-wrap gap-4 text-sm font-medium text-clay-muted">
          <span>累计年度利润：¥{{ formatMoney(selected.cumulativeProfit) }}</span>
          <span>申报状态：{{ selected.filingStatus || '已申报完成' }}</span>
        </div>
      </div>
    </template>
  </section>
</template>

<script setup lang="ts">
import {
  getStatementList,
  getStatementPdfUrl,
  formatMoney,
  type StatementItem
} from '@/api/frontend/compliance/member'
import { ElMessage } from 'element-plus'

defineOptions({ name: 'ComplianceStatement' })

const loading = ref(false)
const list = ref<StatementItem[]>([])
const selected = ref<StatementItem | null>(null)

async function loadData() {
  loading.value = true
  try {
    const res = await getStatementList({ page: 1, pageSize: 24 })
    list.value = res.list || []
    if (list.value.length && !selected.value) {
      selected.value = list.value[0]
    }
  } catch {
    list.value = []
  } finally {
    loading.value = false
  }
}

async function downloadPdf(row: StatementItem) {
  if (row.pdfUrl) {
    window.open(row.pdfUrl, '_blank')
    return
  }
  try {
    const res = await getStatementPdfUrl(row.id)
    if (res.url) window.open(res.url, '_blank')
    else ElMessage.warning('PDF 尚未生成')
  } catch {
    ElMessage.error('下载失败，请稍后重试')
  }
}

onMounted(loadData)
</script>

<style lang="scss" scoped>
.text-clay-foreground { color: #32325d; }
.text-clay-muted { color: #8898aa; }
.text-clay-accent { color: #5a8dee; }
.text-clay-success { color: #71dd37; }
.font-heading { font-family: 'Nunito', 'PingFang SC', sans-serif; }
.shadow-clay-card { box-shadow: 16px 16px 32px rgba(165, 175, 190, 0.3), -10px -10px 24px rgba(255, 255, 255, 0.9); }
.shadow-clay-btn { box-shadow: 12px 12px 24px rgba(90, 141, 238, 0.3), -8px -8px 16px rgba(255, 255, 255, 0.4); }
.shadow-clay-pressed { box-shadow: inset 10px 10px 20px #e0e5ec, inset -10px -10px 20px #ffffff; }
</style>
